import { v } from "convex/values"
import { internal } from "../_generated/api"
import type { Id } from "../_generated/dataModel"
import {
	internalAction,
	internalMutation,
	internalQuery,
} from "../_generated/server"

// Create an agent job
export const createJob = internalMutation({
	args: {
		taskId: v.optional(v.id("tasks")),
		pullRequestId: v.optional(v.id("pullRequests")),
		type: v.union(
			v.literal("chat_response"),
			v.literal("task_analysis"),
			v.literal("code_review"),
			v.literal("auto_fix"),
		),
		input: v.optional(v.any()),
	},
	handler: async (ctx, args) => {
		const jobId = await ctx.db.insert("agentJobs", {
			taskId: args.taskId,
			pullRequestId: args.pullRequestId,
			type: args.type,
			status: "pending",
			input: args.input,
			createdAt: Date.now(),
		})

		return jobId
	},
})

// Update job status to running
export const startJob = internalMutation({
	args: { jobId: v.id("agentJobs") },
	handler: async (ctx, args) => {
		await ctx.db.patch(args.jobId, {
			status: "running",
			startedAt: Date.now(),
		})
	},
})

// Complete a job successfully
export const completeJob = internalMutation({
	args: {
		jobId: v.id("agentJobs"),
		output: v.any(),
	},
	handler: async (ctx, args) => {
		await ctx.db.patch(args.jobId, {
			status: "completed",
			output: args.output,
			completedAt: Date.now(),
		})
	},
})

// Fail a job
export const failJob = internalMutation({
	args: {
		jobId: v.id("agentJobs"),
		errorMessage: v.string(),
	},
	handler: async (ctx, args) => {
		await ctx.db.patch(args.jobId, {
			status: "failed",
			errorMessage: args.errorMessage,
			completedAt: Date.now(),
		})
	},
})

// Load chat context for AI
export const loadChatContext = internalQuery({
	args: {
		projectId: v.optional(v.id("projects")),
		taskId: v.optional(v.id("tasks")),
		limit: v.optional(v.number()),
	},
	handler: async (ctx, args) => {
		const limit = args.limit ?? 20
		let messages: Array<{
			_id: Id<"chatMessages">
			sender: "ai" | "user"
			text: string
			createdAt: number
		}> = []

		if (args.taskId) {
			messages = await ctx.db
				.query("chatMessages")
				.withIndex("by_task", (q) => q.eq("taskId", args.taskId))
				.collect()
		} else if (args.projectId) {
			const allMessages = await ctx.db
				.query("chatMessages")
				.withIndex("by_project", (q) => q.eq("projectId", args.projectId))
				.collect()
			messages = allMessages.filter((m) => m.taskId === undefined)
		}

		const sorted = messages.sort((a, b) => a.createdAt - b.createdAt)
		return sorted.slice(-limit)
	},
})

// Write AI chat response
export const writeChatResponse = internalMutation({
	args: {
		projectId: v.optional(v.id("projects")),
		taskId: v.optional(v.id("tasks")),
		text: v.string(),
	},
	handler: async (ctx, args) => {
		// Get projectId from task if only taskId is provided
		let projectId = args.projectId
		if (args.taskId && !projectId) {
			const task = await ctx.db.get(args.taskId)
			projectId = task?.projectId
		}

		const messageId = await ctx.db.insert("chatMessages", {
			projectId,
			taskId: args.taskId,
			sender: "ai",
			text: args.text,
			createdAt: Date.now(),
		})

		return messageId
	},
})

// Generate chat response via container command
// Note: Real AI responses are handled by containers via the containerCommands table
// This function creates a job record for tracking purposes
export const generateChatResponse = internalAction({
	args: {
		projectId: v.optional(v.id("projects")),
		taskId: v.optional(v.id("tasks")),
		userMessage: v.string(),
	},
	handler: async (
		ctx,
		args,
	): Promise<{ success: boolean; jobId: Id<"agentJobs"> }> => {
		// Create a job record for tracking
		const jobId: Id<"agentJobs"> = await ctx.runMutation(
			internal.internal.aiResponses.createJob,
			{
				taskId: args.taskId,
				type: "chat_response",
				input: { message: args.userMessage },
			},
		)

		await ctx.runMutation(internal.internal.aiResponses.startJob, { jobId })

		try {
			// Load chat context for the container
			const _context = await ctx.runQuery(
				internal.internal.aiResponses.loadChatContext,
				{
					projectId: args.projectId,
					taskId: args.taskId,
					limit: 10,
				},
			)

			// AI responses are generated by containers via containerCommands
			// This job record tracks the request; actual response comes from container
			await ctx.runMutation(internal.internal.aiResponses.completeJob, {
				jobId,
				output: { status: "awaiting_container_response" },
			})

			return { success: true, jobId }
		} catch (error) {
			const message = error instanceof Error ? error.message : "Unknown error"
			await ctx.runMutation(internal.internal.aiResponses.failJob, {
				jobId,
				errorMessage: message,
			})
			throw error
		}
	},
})

// Analyze task and generate acceptance criteria/tests via container
// Note: Actual analysis is performed by containers via containerCommands
export const analyzeTask = internalAction({
	args: { taskId: v.id("tasks") },
	handler: async (
		ctx,
		args,
	): Promise<{ success: boolean; jobId: Id<"agentJobs"> }> => {
		const jobId: Id<"agentJobs"> = await ctx.runMutation(
			internal.internal.aiResponses.createJob,
			{
				taskId: args.taskId,
				type: "task_analysis",
			},
		)

		await ctx.runMutation(internal.internal.aiResponses.startJob, { jobId })

		try {
			// Task analysis is performed by containers via containerCommands
			// This job record tracks the request
			await ctx.runMutation(internal.internal.aiResponses.completeJob, {
				jobId,
				output: { status: "awaiting_container_analysis" },
			})

			return { success: true, jobId }
		} catch (error) {
			const message = error instanceof Error ? error.message : "Unknown error"
			await ctx.runMutation(internal.internal.aiResponses.failJob, {
				jobId,
				errorMessage: message,
			})
			throw error
		}
	},
})

// Run AI code review on PR via container
// Note: Actual code review is performed by containers via containerCommands
export const runCodeReview = internalAction({
	args: { pullRequestId: v.id("pullRequests") },
	handler: async (
		ctx,
		args,
	): Promise<{ success: boolean; jobId: Id<"agentJobs"> }> => {
		const jobId: Id<"agentJobs"> = await ctx.runMutation(
			internal.internal.aiResponses.createJob,
			{
				pullRequestId: args.pullRequestId,
				type: "code_review",
			},
		)

		await ctx.runMutation(internal.internal.aiResponses.startJob, { jobId })

		try {
			// Code review is performed by containers via containerCommands
			// This job record tracks the request
			await ctx.runMutation(internal.internal.aiResponses.completeJob, {
				jobId,
				output: { status: "awaiting_container_review" },
			})

			return { success: true, jobId }
		} catch (error) {
			const message = error instanceof Error ? error.message : "Unknown error"
			await ctx.runMutation(internal.internal.aiResponses.failJob, {
				jobId,
				errorMessage: message,
			})
			throw error
		}
	},
})

// Generate auto-fix for an issue via container
// Note: Actual fix generation is performed by containers via containerCommands
export const autoFixIssue = internalAction({
	args: { issueId: v.id("prIssues") },
	handler: async (
		ctx,
		args,
	): Promise<{ success: boolean; jobId: Id<"agentJobs"> }> => {
		const jobId: Id<"agentJobs"> = await ctx.runMutation(
			internal.internal.aiResponses.createJob,
			{
				type: "auto_fix",
				input: { issueId: args.issueId },
			},
		)

		await ctx.runMutation(internal.internal.aiResponses.startJob, { jobId })

		try {
			// Auto-fix generation is performed by containers via containerCommands
			// This job record tracks the request
			await ctx.runMutation(internal.internal.aiResponses.completeJob, {
				jobId,
				output: { status: "awaiting_container_fix" },
			})

			return { success: true, jobId }
		} catch (error) {
			const message = error instanceof Error ? error.message : "Unknown error"
			await ctx.runMutation(internal.internal.aiResponses.failJob, {
				jobId,
				errorMessage: message,
			})
			throw error
		}
	},
})
